apiVersion: apps/v1
kind: Deployment
metadata:
  name: wolfram-web
  labels:
    app: wolfram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wolfram
  template:
    metadata:
      labels:
        app: wolfram
    spec:
      containers:
        - name: wolfram-student-info-portal
          image: manguilar22/nginx:wolfram
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wolfram-web-svc
  labels:
    app: wolfram
spec:
  type: NodePort
  selector:
    app: wolfram
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001